stages:
  - build_html
  - deploy

pages:
  stage: deploy
  tags:
    - debian
    - buster
  artifacts:
    paths:
      - "public"
  script:
    - mkdir -v public
    - cp -fv html/* public/

build_html:
  stage: build_html
  tags:
    - debian
    - buster
  artifacts:
    untracked: false
    paths:
      - "html/"
  script: "./ci_build_html.sh"
