# GCP Cloud Build configuration, run:
#
# use:
#   gcloud builds submit .
steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --destination=gcr.io/$PROJECT_ID/tokyodebian-team-pages-builder
    - --cache=true
    - --dockerfile=Dockerfile
- name: 'gcr.io/$PROJECT_ID/tokyodebian-team-pages-builder'
  id: 'build'
  entrypoint: '/bin/bash'
  args: ['./ci_build_html.sh']
